name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Run this workflow when there is a push to teambit/bit master
  repository_dispatch:
    types: [ bit_master_push ]

env:
  BIT_TOKEN: ${{ secrets.BIT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    container:
      image: docker://bitcli/bit:latest
    steps:
      - uses:  teambit/setup-action@v1
        with:
          name: angular-github-actions
          BIT_TOKEN: ${{ env.BIT_TOKEN }}

      - uses: actions/checkout@v2

      - name: Add example app
        run: bit add examples/demo-lib

      - name: Install dependencies
        run: bit install

      # Compile the aspects
      - name: Bit compile aspects
        run: bit compile ng-packagr angular-eslint-config angular angular-v11 angular-v12

      # Run bit link to regenerate the package.json of the example component
      - name: Bit link
        run: bit link

      # Compile the example component
      - name: Bit compile example
        run: bit compile demo-lib

      - name: Bit test
        run: bit test

      - name: Bit build
        run: bit build

      - uses: actions/upload-artifact@v2
        with:
          name: debug-log
          path: $HOME/Library/Caches/Bit/logs
